spring:
  datasource:
    url: jdbc:h2:mem:local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # 启动时如果没有表，会自动根据实体类创建表;如果有结构变化，会自动更新
    show-sql: true  # 打印 SQL 语句到控制台

  # 本地开发，H2 + JPA 自带的 ddl-auto 功能可以自动建表。
  h2:
    console:
      enabled: true
      path: /h2-console   # http://localhost:8080/h2-console

  flyway:
    enabled: false  # 真实工程模式，数据库版本管理工具
    locations: classpath:db/migration
    datasource:
      url: jdbc:h2:mem:local
      user: sa
      password:

server:
  port: 8080

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html